export {default as ContactUs} from './ContactUs'
export {default as Error} from './Error'
export {default as Footer} from './HomePage/Footer'
export {default as Header} from './HomePage/Header'
export {default as Home} from './HomePage/Home'
export {default as OurServices} from './Servies_Pages/OurServices'
export {default as OurTeams} from './OurTeams'
export {default as Testimonials} from './Testimonials'